onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

# Workspace packages. We include both root-level and inner corAe-Studio layout
packages:
  - "apps/*"
  - "packages/*"
  - "corAe-Studio/apps/*"
  - "corAe-Studio/packages/*"
