// patch-chunks.cjs — auto-generated by corAe BuildOps
const fs = require('fs');
const path = require('path');

const serverDir = path.join(__dirname, '..', '.next', 'server');
const chunksDir = path.join(serverDir, 'chunks');
const checkMode = process.argv.includes('--check');

function log(...args) { console.log('[patch-chunks]', ...args); }
function ensureDir(d) { try { fs.mkdirSync(d, { recursive: true }); } catch (e) {} }

if (!fs.existsSync(chunksDir)) {
  log('No chunks directory found at', chunksDir);
  process.exit(0);
}

ensureDir(serverDir);

const files = fs.readdirSync(chunksDir).filter(f => f.endsWith('.js'));
let missing = 0;

for (const f of files) {
  const id = f.replace(/\.js$/, '');
  const wrapperPath = path.join(serverDir, `${id}.js`);
  const rel = `./chunks/${f}`;
  const content = `// Auto-created wrapper to forward to ${rel}\ntry {\n  module.exports = require('${rel}');\n} catch (e) {\n  e.message = ` + "`While resolving wrapper ${id}.js -> ${rel}: ${e.message}` + `" + `"` + `;\n  throw e;\n}\n`;

  if (checkMode) {
    if (!fs.existsSync(wrapperPath) || !fs.existsSync(path.join(chunksDir, f))) {
      console.error(`❌ Missing wrapper or chunk for ${f}`);
      missing++;
    }
    continue;
  }

  try {
    fs.writeFileSync(wrapperPath, content, { encoding: 'utf8' });
    log('Wrote wrapper', wrapperPath);
  } catch (err) {
    console.error('[patch-chunks] error writing', wrapperPath, err.message);
  }
}

if (checkMode) {
  if (missing === 0) {
    console.log('✅ All chunk wrappers verified.');
    process.exit(0);
  } else {
    console.error(`❌ ${missing} wrappers missing.`);
    process.exit(1);
  }
} else {
  log('Done. Created', files.length, 'wrappers.');
}
